GET  http://localhost:3000/boulders

###
POST http://localhost:3000/boulders
content-type: application/json

{
    "name": "The One", 
    "description": "Bouldery Boulder",
    "imgUrl":  "http://thisisboulderimage.com",
    "bGrade": "7B+"
}

###
GET  http://localhost:3000/boulders/63d648df7aee3154c89dc546

###
PATCH  http://localhost:3000/boulders/63d648df7aee3154c89dc546
content-type: application/json

{
    "name": "this is ameriCA", 
    "description": "rwgwrgwreg",
    "imgUrl": "http://thisisboulderimage.com"
}

###
DELETE  http://localhost:3000/boulders/63d648df7aee3154c89dc546

###
POST http://localhost:3000/boulders/63d6c20b780318843a67a541/ratings
content-type: application/json

{
    "rating": 1
}
###
PATCH  http://localhost:3000/boulders/63d648df7aee3154c89dc546/grades/propose-grade
content-type: application/json

{
    "grade": "8A"
}
###
PATCH  http://localhost:3000/boulders/63d648df7aee3154c89dc546/grades/change-grade
content-type: application/json

{
    "grade": "7A"
}
###




