
###
POST http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders
content-type: application/json

{
    "name": "The Two", 
    "description": "Bouldery Boulder",
    "imgUrl":  "http://thisisboulderimage.com",
    "bGrade": "7B+"
}
###
GET http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders
###
GET http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders/63da77f16d061a3dfb599058
###
PATCH http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders/63da77f16d061a3dfb599058
content-type: application/json

{
    "name": "wrgwrhg", 
    "description": "ffffffff",
    "imgUrl": "http://tsrwghimage.com",
    "bGrade": "8A+"
}

###
DELETE  http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders/63da77f16d061a3dfb599058

###
POST http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders/63da77f16d061a3dfb599058/ratings
content-type: application/json

{
    "rating": 1
}
###
PATCH  http://localhost:3000/gyms/63da64ca8db6850f875cbace/walls/63da64de8db6850f875cbad1/boulders/63da77f16d061a3dfb599058/grades
content-type: application/json

{
    "grade": "8A"
}
###





