POST  http://localhost:3000/gyms/63d6e656b25f2b8b96da8240/walls
content-type: application/json

{
    "name": "etjetje",
    "description": "etjetjetje",
    "angle": "15"
}
###
GET http://localhost:3000/gyms/63d6e656b25f2b8b96da8240/walls
###
PATCH http://localhost:3000/gyms/63d6e656b25f2b8b96da8240/walls/63d796dfe5a28e2fb63434fc/ratings
content-type: application/json

{
    "rating": 2
}
###
PATCH http://localhost:3000/gyms/63d6e656b25f2b8b96da8240/walls/63d796dfe5a28e2fb63434fc
content-type: application/json

{
    "name":"this is american wall",
    "description": "A wall of Hikes",
    "angle": 20
}